### ISSUE TITLE
Resetting password to too short password

### ISSUE THREAD

**Issue by cyyv** [chenPerach/Scouting_App_Off_Season#12]
When you reset the password you can choose a 6-character password, and when you try to log in with it you get an error message that says it's not secure enough.

**To Reproduce**
1. Reset password
2. Choose 6-character password
3. Try to login

**Expected behavior**
Don't.

**Additional context**
Please add space between the teams numbers.

**Comment by chenPerach** [comment]
will be fixed in the next update

**Comment by chenPerach** [comment]
# what caused the problem

fire base handles the entire password reset process in the app,
seems like the only requirement for a password to be secure in firebase is if that password has 6+ characters in it.
right now i don't see a nice way to give you own validation script to firebase, this may cause a problem.

if your password was reset with hebrew characters (or any other langauge that is not hebrew for that matter)
 
this will be fixed by only requiring the user to give a 6+ char password.

**Comment by chenPerach** [comment]
I think that [this stack overflow comment](https://stackoverflow.com/a/60013966/12593028) is relevent to the conversation.

**Comment by chenPerach** [comment]
[fixed](https://github.com/chenPerach/Scouting_App_Off_Season/commit/391e1d0d554a491d2f0a4777d26051b19c8ad937)
